# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: jxcb.xyz deployment

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    defaults:
      run:
        shell: bash
        working-directory: buildtmp
    steps:
      - uses: actions/checkout@v3
      - name: nodejs
        uses: https://github.com/actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: build site
        working-directory: ./release
        run: |
          npm ci
          npm run build
      - name: copy built site to host directory
        run: |
          cp ./release/* /home/jxcb/www/tmp
          touch /home/jxcb/www/tmp/workdir
          pwd > /home/jxcb/www/tmp/workdir
